name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build-gitD
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ github.event.push.ref == 'refs/heads/master' && secrets.FIREBASE_SERVICE_ACCOUNT_OPENSOURCEFESTIVAL2023 || secrets.FIREBASE_SERVICE_ACCOUNT_OPENSOURCEFESTIVAL2023_DEV }}
          channelId: live
          projectId: ${{ github.event.push.ref == 'refs/heads/master' && 'opensourcefestival2023' || 'opensourcefestival2023-dev' }}
